from enum import Enum


class ListenerCode(Enum):
    PROGRAM_DID_START = -1
    DID_PICKED_IMAGE = 0
    DID_LOAD_IMAGE = 1
    REFRESH_VIEW_IMAGE_METADATA = 2
    SLICE_VIEW_DID_CHANGE = 3
    SHOW_IMAGE_METADATA = 4
    CINEMA_MODE_WILL_START = 5
    CINEMA_MODE_WILL_STOP = 6
    PRINT_IMAGE_SLICE = 7
    NOISE_THRESHOLD_DID_CHANGE = 8
    PRINT_NOISE_THRESHOLD = 9
    CONTRAST_VALUE_DID_CHANGE = 10
    SHOW_DISTANCE_TOOLS = 11
    POINT_DISTANCE_DID_CHANGE = 12
